language: python
python:
  - "2.7"

install:
  - pip install pep8
  - pip install -r requirements.txt

before_script:
  - pep8 --version
  - sudo mkdir -p /var/log/irma/ && sudo touch /var/log/irma/sqlalchemy.log && sudo chmod 555 /var/log/irma/sqlalchemy.log
  - export IRMA_FRONTEND_CFG_PATH=tests/

script:
  - pep8 config extras frontend tests --exclude=tests/old,extras/migration
  - nosetests tests/

notifications:
  email:
    on_success: never
